Repository AdoptOpenJDK/openjdk-docker, pull requests merged in 2019-05, with the labels that each got.

#138 Implements debian as an additional docker image for all arches #136
  common_functions.sh
  config/hotspot.config
  config/openj9.config
  config/tags.config
  dockerfile_functions.sh
  update_multiarch.sh
Labels: TSC-Agenda, enhancement

#140 add windows support
  .appveyor.yml
  .gitignore
  .travis.yml
  common_functions.sh
  config/hotspot.config
  config/openj9.config
  config/tags.config
  dockerfile_functions.sh
  update_multiarch.sh
Labels: enhancement

#144 fix#111 - Add missing locales
  dockerfile_functions.sh
Labels: bug

#150 feat: #139 - Keep jcmd in slim variants
  10/jdk/alpine/slim-java_bin_del.list
  10/jdk/ubuntu/slim-java_bin_del.list
  11/jdk/alpine/slim-java_bin_del.list
  11/jdk/ubuntu/slim-java_bin_del.list
  12/jdk/alpine/slim-java_bin_del.list
  12/jdk/ubuntu/slim-java_bin_del.list
  8/jdk/alpine/slim-java_bin_del.list
  8/jdk/ubuntu/slim-java_bin_del.list
  9/jdk/alpine/slim-java_bin_del.list
  9/jdk/ubuntu/slim-java_bin_del.list
  config/slim-java_bin_del.list
Labels: enhancement

#149 Add script to create Dockerfiles for all supported versions.
  common_functions.sh
  update_all.sh
  update_multiarch.sh
Labels: enhancement

#160 Manifest tweaks for windows dockerfiles
  .gitignore
  common_functions.sh
  generate_manifest_script.sh
Labels: enhancement

#155 fix: #105 - Set locale in alpine image
  dockerfile_functions.sh
Labels: enhancement

#90 Use `#!/usr/bin/env bash` instead of `#!/bin/bash`
  10/jdk/alpine/slim-java.sh
  10/jdk/ubuntu/slim-java.sh
  11/jdk/alpine/slim-java.sh
  11/jdk/ubuntu/slim-java.sh
  8/jdk/alpine/slim-java.sh
  8/jdk/ubuntu/slim-java.sh
  9/jdk/alpine/slim-java.sh
  9/jdk/ubuntu/slim-java.sh
  build_all.sh
  build_latest.sh
  common_functions.sh
  dockerfile_functions.sh
  generate_latest_sums.sh
  generate_manifest_script.sh
  slim-java.sh
  test_all.sh
  test_multiarch.sh
  update_manifest_all.sh
  update_multiarch.sh
Labels: enhancement

#169 Update OpenJ9 Java 8 to 0.14.2, update shasums for all to latest.
  11/jdk/alpine/Dockerfile.hotspot.nightly.full
  11/jdk/alpine/Dockerfile.hotspot.nightly.slim
  11/jdk/alpine/Dockerfile.openj9.nightly.full
  11/jdk/alpine/Dockerfile.openj9.nightly.slim
  11/jdk/debian/Dockerfile.hotspot.nightly.full
  11/jdk/debian/Dockerfile.hotspot.nightly.slim
  11/jdk/debian/Dockerfile.openj9.nightly.full
  11/jdk/debian/Dockerfile.openj9.nightly.slim
  11/jdk/ubuntu/Dockerfile.hotspot.nightly.full
  11/jdk/ubuntu/Dockerfile.hotspot.nightly.slim
  11/jdk/ubuntu/Dockerfile.openj9.nightly.full
  11/jdk/ubuntu/Dockerfile.openj9.nightly.slim
  11/jdk/windows/Dockerfile.hotspot.nightly.full
  11/jdk/windows/Dockerfile.openj9.nightly.full
  11/jre/alpine/Dockerfile.hotspot.nightly.full
  11/jre/alpine/Dockerfile.openj9.nightly.full
  11/jre/debian/Dockerfile.hotspot.nightly.full
  11/jre/debian/Dockerfile.openj9.nightly.full
  11/jre/ubuntu/Dockerfile.hotspot.nightly.full
  11/jre/ubuntu/Dockerfile.openj9.nightly.full
  12/jdk/alpine/Dockerfile.hotspot.nightly.full
  12/jdk/alpine/Dockerfile.hotspot.nightly.slim
  12/jdk/debian/Dockerfile.hotspot.nightly.full
  12/jdk/debian/Dockerfile.hotspot.nightly.slim
  12/jdk/ubuntu/Dockerfile.hotspot.nightly.full
  12/jdk/ubuntu/Dockerfile.hotspot.nightly.slim
  12/jdk/windows/Dockerfile.hotspot.nightly.full
  12/jre/alpine/Dockerfile.hotspot.nightly.full
  12/jre/debian/Dockerfile.hotspot.nightly.full
  12/jre/ubuntu/Dockerfile.hotspot.nightly.full
  8/jdk/alpine/Dockerfile.hotspot.nightly.full
  8/jdk/alpine/Dockerfile.hotspot.nightly.slim
  8/jdk/alpine/Dockerfile.openj9.nightly.full
  8/jdk/alpine/Dockerfile.openj9.nightly.slim
  8/jdk/alpine/Dockerfile.openj9.releases.full
  8/jdk/alpine/Dockerfile.openj9.releases.slim
  8/jdk/debian/Dockerfile.hotspot.nightly.full
  8/jdk/debian/Dockerfile.hotspot.nightly.slim
  8/jdk/debian/Dockerfile.openj9.nightly.full
  8/jdk/debian/Dockerfile.openj9.nightly.slim
  8/jdk/debian/Dockerfile.openj9.releases.full
  8/jdk/debian/Dockerfile.openj9.releases.slim
  8/jdk/ubuntu/Dockerfile.hotspot.nightly.full
  8/jdk/ubuntu/Dockerfile.hotspot.nightly.slim
  8/jdk/ubuntu/Dockerfile.openj9.nightly.full
  8/jdk/ubuntu/Dockerfile.openj9.nightly.slim
  8/jdk/ubuntu/Dockerfile.openj9.releases.full
  8/jdk/ubuntu/Dockerfile.openj9.releases.slim
  8/jdk/windows/Dockerfile.hotspot.nightly.full
  8/jdk/windows/Dockerfile.openj9.nightly.full
  8/jdk/windows/Dockerfile.openj9.releases.full
  8/jre/alpine/Dockerfile.hotspot.nightly.full
  8/jre/alpine/Dockerfile.openj9.nightly.full
  8/jre/alpine/Dockerfile.openj9.releases.full
  8/jre/debian/Dockerfile.hotspot.nightly.full
  8/jre/debian/Dockerfile.openj9.nightly.full
  8/jre/debian/Dockerfile.openj9.releases.full
  8/jre/ubuntu/Dockerfile.hotspot.nightly.full
  8/jre/ubuntu/Dockerfile.openj9.nightly.full
  8/jre/ubuntu/Dockerfile.openj9.releases.full
Labels: enhancement

#170 Remove all downloaded temporary Alpine apk files.
  dockerfile_functions.sh
Labels: enhancement
