Repository AdoptOpenJDK/openjdk-docker, pull requests merged in 2020-09, with the labels that each got.

#399 Add hotspot 15 build changes.
  common_functions.sh
  config/hotspot-official.config
  config/hotspot.config
Labels: Release

#405 Build OpenJ9 version 15 images and deprecate 13.
  config/openj9-official.config
  config/openj9.config
Labels: Release

#409 Fix official docker image build failures.
  build_latest.sh
  dockerfile_functions.sh
  dockerhub_doc_config_update.sh
  update_multiarch.sh
Labels: bug

#413 Avoid copying scc script to directory on windows
  build_latest.sh
  update_multiarch.sh
Labels: bug

#414 Remove the use of unsupported powershell based images in older dockerfiles.
  13/jdk/windows/nanoserver-1809/Dockerfile.hotspot.nightly.full
  13/jdk/windows/nanoserver-1809/Dockerfile.hotspot.releases.full
  13/jre/windows/nanoserver-1809/Dockerfile.hotspot.nightly.full
  13/jre/windows/nanoserver-1809/Dockerfile.hotspot.releases.full
  14/jdk/windows/nanoserver-1809/Dockerfile.hotspot.nightly.full
  14/jdk/windows/nanoserver-1809/Dockerfile.hotspot.nightly.slim
  14/jdk/windows/nanoserver-1809/Dockerfile.openj9.nightly.full
  14/jdk/windows/nanoserver-1809/Dockerfile.openj9.nightly.slim
  14/jdk/windows/nanoserver-1909/Dockerfile.hotspot.nightly.full
  14/jdk/windows/nanoserver-1909/Dockerfile.hotspot.nightly.slim
  14/jdk/windows/nanoserver-1909/Dockerfile.openj9.nightly.full
  14/jdk/windows/nanoserver-1909/Dockerfile.openj9.nightly.slim
  14/jre/windows/nanoserver-1809/Dockerfile.hotspot.nightly.full
  14/jre/windows/nanoserver-1809/Dockerfile.hotspot.nightly.slim
  14/jre/windows/nanoserver-1809/Dockerfile.openj9.nightly.full
  14/jre/windows/nanoserver-1809/Dockerfile.openj9.nightly.slim
  14/jre/windows/nanoserver-1909/Dockerfile.hotspot.nightly.full
  14/jre/windows/nanoserver-1909/Dockerfile.hotspot.nightly.slim
  14/jre/windows/nanoserver-1909/Dockerfile.openj9.nightly.full
  14/jre/windows/nanoserver-1909/Dockerfile.openj9.nightly.slim
  8/jdk/windows/nanoserver-1809/Dockerfile.hotspot.releases.slim
  8/jdk/windows/nanoserver-1809/Dockerfile.openj9.releases.full
  8/jdk/windows/nanoserver-1809/Dockerfile.openj9.releases.slim
  8/jre/windows/nanoserver-1809/Dockerfile.hotspot.releases.slim
  8/jre/windows/nanoserver-1809/Dockerfile.openj9.releases.full
  8/jre/windows/nanoserver-1809/Dockerfile.openj9.releases.slim
Labels: bug

#407 Fixs issue 404 - Makes scc accessible to non-root user
  generate_openj9_scc.sh
Labels: enhancement

#418 swap ppc64le builds to use dynamic hosts
  Jenkinsfile
Labels: enhancement

#408 Fixs issue 403 - Removing default options from JAVA_TOOL_OPTIONS
  dockerfile_functions.sh
Labels: bug

#417 Changing scc directory permission to 777
  generate_openj9_scc.sh
Labels: bug

#422 Removing eclipse specific mechanism due to longer build time issue
  generate_openj9_scc.sh
Labels: bug
