Repository AdoptOpenJDK/openjdk-docker, pull requests merged in 2020-10, with the labels that each got.

#427 Make sure bash and curl are present before running the generate_openj9_scc.sh script on Alpine images
  dockerfile_functions.sh
Labels: bug

#433 Make major version determination, version independent.
  slim-java.sh
Labels: bug

#434 Add JDK 15 to Github Actions matrix
  .github/workflows/continuous-integration-workflow.yml
Labels: enhancement

#436 Redirect java stderr while parsing version
  slim-java.sh
Labels: bug

#438 Add SCC generation code to the dockerfile and remove the external script
  dockerfile_functions.sh
Labels: enhancement

#441 Adds comment, sets shell back to sh, better linespacing for readability
  dockerfile_functions.sh
Labels: bug

#446 Rollback ubuntu version to `bionic` (18.04) to fix the official image tags.
  dockerfile_functions.sh
Labels: bug

#449 Fix unofficial image dockerhub slim tag documentation entries.
  dockerhub_doc_config_update.sh
Labels: bug

#451 Move to Ubuntu 20.04 (focal) as base image
  dockerfile_functions.sh
  dockerhub_doc_config_update.sh
Labels: enhancement

#453 Adding a flag 'runtype' to set the oses for PR build
  .appveyor.yml
  .github/workflows/continuous-integration-workflow.yml
  .travis.yml
  build_all.sh
  build_latest.sh
  common_functions.sh
Labels: enhancement

#456 Update Dockerfiles to handle hotspot respin (11.0.9+11.1)
  11/jdk/alpine/Dockerfile.hotspot.releases.full
  11/jdk/alpine/Dockerfile.hotspot.releases.slim
  11/jdk/centos/Dockerfile.hotspot.releases.full
  11/jdk/centos/Dockerfile.hotspot.releases.slim
  11/jdk/clefos/Dockerfile.hotspot.releases.full
  11/jdk/clefos/Dockerfile.hotspot.releases.slim
  11/jdk/debian/Dockerfile.hotspot.releases.full
  11/jdk/debian/Dockerfile.hotspot.releases.slim
  11/jdk/debianslim/Dockerfile.hotspot.releases.full
  11/jdk/debianslim/Dockerfile.hotspot.releases.slim
  11/jdk/leap/Dockerfile.hotspot.releases.full
  11/jdk/tumbleweed/Dockerfile.hotspot.releases.full
  11/jdk/ubi-minimal/Dockerfile.hotspot.releases.full
  11/jdk/ubi/Dockerfile.hotspot.releases.full
  11/jdk/ubi/Dockerfile.hotspot.releases.slim
  11/jdk/ubuntu/Dockerfile.hotspot.releases.full
  11/jdk/ubuntu/Dockerfile.hotspot.releases.slim
  11/jdk/windows/nanoserver-1809/Dockerfile.hotspot.releases.full
  11/jdk/windows/windowsservercore-1809/Dockerfile.hotspot.releases.full
  11/jdk/windows/windowsservercore-ltsc2016/Dockerfile.hotspot.releases.full
  11/jre/alpine/Dockerfile.hotspot.releases.full
  11/jre/centos/Dockerfile.hotspot.releases.full
  11/jre/clefos/Dockerfile.hotspot.releases.full
  11/jre/debian/Dockerfile.hotspot.releases.full
  11/jre/debianslim/Dockerfile.hotspot.releases.full
  11/jre/leap/Dockerfile.hotspot.releases.full
  11/jre/tumbleweed/Dockerfile.hotspot.releases.full
  11/jre/ubi-minimal/Dockerfile.hotspot.releases.full
  11/jre/ubi/Dockerfile.hotspot.releases.full
  11/jre/ubuntu/Dockerfile.hotspot.releases.full
  11/jre/windows/nanoserver-1809/Dockerfile.hotspot.releases.full
  11/jre/windows/windowsservercore-1809/Dockerfile.hotspot.releases.full
  11/jre/windows/windowsservercore-ltsc2016/Dockerfile.hotspot.releases.full
  15/jdk/debian/Dockerfile.hotspot.releases.full
  8/jdk/windows/windowsservercore-1809/Dockerfile.hotspot.releases.full
Labels: Release
