Repository AdoptOpenJDK/openjdk-docker, pull requests merged in 2020-04, with the labels that each got.

#313 Add timestamps and more verbose messages to each step of the build_all.sh
  build_all.sh
Labels: enhancement

#315 Remove trailing backslash as it is not needed.
  test_multiarch.sh
Labels: bug

#312 Add checks to rebuild docker images only if needed.
  .gitignore
  build_all.sh
  build_latest.sh
  common_functions.sh
  test_all.sh
  update_all.sh
  update_manifest_all.sh
Labels: enhancement

#320 Log key dates that decide whether a docker image is built.
  build_latest.sh
Labels: enhancement

#306 Stop building Version 13 docker nightly images.
  .appveyor.yml
  .travis.yml
  config/hotspot.config
  config/openj9.config
Labels: enhancement

#325 Add 14.0.1_7 hotspot shasums.
  14/jdk/alpine/Dockerfile.hotspot.releases.full
  14/jdk/alpine/Dockerfile.hotspot.releases.slim
  14/jdk/centos/Dockerfile.hotspot.releases.full
  14/jdk/centos/Dockerfile.hotspot.releases.slim
  14/jdk/clefos/Dockerfile.hotspot.releases.full
  14/jdk/clefos/Dockerfile.hotspot.releases.slim
  14/jdk/debian/Dockerfile.hotspot.releases.full
  14/jdk/debian/Dockerfile.hotspot.releases.slim
  14/jdk/debianslim/Dockerfile.hotspot.releases.full
  14/jdk/debianslim/Dockerfile.hotspot.releases.slim
  14/jdk/ubi-minimal/Dockerfile.hotspot.releases.full
  14/jdk/ubi-minimal/Dockerfile.openj9.releases.full
  14/jdk/ubi/Dockerfile.hotspot.releases.full
  14/jdk/ubi/Dockerfile.hotspot.releases.slim
  14/jdk/ubuntu/Dockerfile.hotspot.releases.full
  14/jdk/ubuntu/Dockerfile.hotspot.releases.slim
  14/jdk/windows/nanoserver-1809/Dockerfile.hotspot.releases.full
  14/jdk/windows/windowsservercore-1809/Dockerfile.hotspot.releases.full
  14/jdk/windows/windowsservercore-1809/Dockerfile.openj9.nightly.full
  14/jdk/windows/windowsservercore-ltsc2016/Dockerfile.hotspot.releases.full
  14/jdk/windows/windowsservercore-ltsc2016/Dockerfile.openj9.nightly.full
  14/jre/alpine/Dockerfile.hotspot.releases.full
  14/jre/centos/Dockerfile.hotspot.releases.full
  14/jre/clefos/Dockerfile.hotspot.releases.full
  14/jre/debian/Dockerfile.hotspot.releases.full
  14/jre/debianslim/Dockerfile.hotspot.releases.full
  14/jre/ubi-minimal/Dockerfile.hotspot.releases.full
  14/jre/ubi/Dockerfile.hotspot.releases.full
  14/jre/ubuntu/Dockerfile.hotspot.releases.full
  14/jre/windows/nanoserver-1809/Dockerfile.hotspot.releases.full
  14/jre/windows/windowsservercore-1809/Dockerfile.hotspot.releases.full
  14/jre/windows/windowsservercore-1809/Dockerfile.openj9.nightly.full
  14/jre/windows/windowsservercore-ltsc2016/Dockerfile.hotspot.releases.full
  14/jre/windows/windowsservercore-ltsc2016/Dockerfile.openj9.nightly.full
Labels: Release

#330 Update UBI and UBI-Minimal to version 8.2
  dockerfile_functions.sh
Labels: enhancement
