Repository AdoptOpenJDK/openjdk-docker, pull requests merged in 2021-04, with the labels that each got.

#535 Add support for musl based native alpine docker images.
  README.md
  build_latest.sh
  common_functions.sh
  dockerfile_functions.sh
  generate_manifest_script.sh
  update_multiarch.sh
Labels: enhancement

#541 tag_aliases was mistakenly labeled as a local variable.
  common_functions.sh
Labels: bug

#542 Add "os family" functionality to the test script.
  test_multiarch.sh
Labels: bug

#540 Remove alpine OS provided java-cacerts as we dont use it.
  dockerfile_functions.sh
Labels: bug

#543 Rolling back ubuntu version to 18.04 on armv7l due to GPG error
  dockerfile_functions.sh
Labels: bug

#506 Add updated release process in RELEASE.md
  RELEASE.md
Labels: enhancement

#525 Adds the build and manifest process doc
  build_process.md
  manifest_process.md
Labels: enhancement

#548 Update windows ltsc dockerfiles to use wget instead of curl.
  11/jdk/windows/windowsservercore-1809/Dockerfile.hotspot.releases.full
  11/jdk/windows/windowsservercore-1809/Dockerfile.openj9.releases.full
  11/jdk/windows/windowsservercore-ltsc2016/Dockerfile.hotspot.releases.full
  11/jdk/windows/windowsservercore-ltsc2016/Dockerfile.openj9.releases.full
  11/jre/windows/windowsservercore-1809/Dockerfile.hotspot.releases.full
  11/jre/windows/windowsservercore-1809/Dockerfile.openj9.releases.full
  11/jre/windows/windowsservercore-ltsc2016/Dockerfile.hotspot.releases.full
  11/jre/windows/windowsservercore-ltsc2016/Dockerfile.openj9.releases.full
  14/jdk/windows/windowsservercore-1809/Dockerfile.hotspot.releases.full
  14/jdk/windows/windowsservercore-1809/Dockerfile.openj9.releases.full
  14/jdk/windows/windowsservercore-ltsc2016/Dockerfile.hotspot.releases.full
  14/jdk/windows/windowsservercore-ltsc2016/Dockerfile.openj9.releases.full
  14/jre/windows/windowsservercore-1809/Dockerfile.hotspot.releases.full
  14/jre/windows/windowsservercore-1809/Dockerfile.openj9.releases.full
  14/jre/windows/windowsservercore-ltsc2016/Dockerfile.hotspot.releases.full
  14/jre/windows/windowsservercore-ltsc2016/Dockerfile.openj9.releases.full
  15/jdk/windows/windowsservercore-1809/Dockerfile.hotspot.releases.full
  15/jdk/windows/windowsservercore-1809/Dockerfile.openj9.releases.full
  15/jdk/windows/windowsservercore-ltsc2016/Dockerfile.hotspot.releases.full
  15/jdk/windows/windowsservercore-ltsc2016/Dockerfile.openj9.releases.full
  15/jre/windows/windowsservercore-1809/Dockerfile.hotspot.releases.full
  15/jre/windows/windowsservercore-1809/Dockerfile.openj9.releases.full
  15/jre/windows/windowsservercore-ltsc2016/Dockerfile.hotspot.releases.full
  15/jre/windows/windowsservercore-ltsc2016/Dockerfile.openj9.releases.full
  16/jdk/windows/windowsservercore-1809/Dockerfile.hotspot.releases.full
  16/jdk/windows/windowsservercore-1809/Dockerfile.openj9.releases.full
  16/jdk/windows/windowsservercore-ltsc2016/Dockerfile.hotspot.releases.full
  16/jdk/windows/windowsservercore-ltsc2016/Dockerfile.openj9.releases.full
  16/jre/windows/windowsservercore-1809/Dockerfile.hotspot.releases.full
  16/jre/windows/windowsservercore-1809/Dockerfile.openj9.releases.full
  16/jre/windows/windowsservercore-ltsc2016/Dockerfile.hotspot.releases.full
  16/jre/windows/windowsservercore-ltsc2016/Dockerfile.openj9.releases.full
  8/jdk/centos/Dockerfile.hotspot.releases.full
  8/jdk/windows/windowsservercore-1809/Dockerfile.hotspot.releases.full
  8/jdk/windows/windowsservercore-1809/Dockerfile.openj9.releases.full
  8/jdk/windows/windowsservercore-ltsc2016/Dockerfile.hotspot.releases.full
  8/jdk/windows/windowsservercore-ltsc2016/Dockerfile.openj9.releases.full
  8/jre/windows/windowsservercore-1809/Dockerfile.hotspot.releases.full
  8/jre/windows/windowsservercore-1809/Dockerfile.openj9.releases.full
  8/jre/windows/windowsservercore-ltsc2016/Dockerfile.hotspot.releases.full
  8/jre/windows/windowsservercore-ltsc2016/Dockerfile.openj9.releases.full
Labels: Release, bug

#551 Removing TARGET_ARCHITECTURE to avoid cross platform image build on x64 for armv7l JDK 16
  Jenkinsfile
Labels: bug

#558 add updater github action
  .github/workflows/updater.yml
Labels: enhancement
